### ISSUE TITLE
Library Roadmap

### ISSUE THREAD

**Issue by simnalamburt** [openirc/qbirc#1]
### 1. Fix
- [x] Fix urgent security vulnerability
- [x] Make `npm test` work properly
- [x] Enable travis CI
- [ ] Introduce babel, use ES2015
- [ ] Introduce optional type checking, [flow](http://flowtype.org/)
### 2. Rebrand Library
- [x] Rename: slate-irc &rarr; qbirc
- [x] `npm publish`
- [x] ~~Publish 1.0~~ &rarr; Merged into [slate-irc]
- [x] ~~_(Optional)_ Go to reddit or somewhere to get some reputation~~ &rarr; Merged into [slate-irc]
### 3. Features
- [x] Support [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) &rarr; #12
- [x] Support IRCv3.1, IRCv3.2 &rarr; #3 

[slate-irc]: https://github.com/slate/slate-irc
